### ISSUE TITLE
Wordpress Transition

### ISSUE THREAD

**Issue by quentin-f451** [dept/highway#49]
Hi there!
I'm facing some issues when transforming a perfectly working static website using Highway to a Wordpress website.
On click on a link that would trigger a transition to another page, nothing is happening and I got the following error 

`
Uncaught (in promise) TypeError: Cannot read property 'href' of undefined
`

in this function that perfectly works with my static website: 

`
H.on('NAVIGATE_IN', (to, location) => {
    console.log(location.href);
  });
`

Is there anything to know about using Highway with Wordpress?
Thanks a lot.

**Comment by Anthodpnt** [comment]
Hi @quentin-f451,

The issue is not related to Wordpress but to a breaking change in the last release about the structure of the events callback parameters. We changed it to be more flexible.

Now in the [v2.1.2](https://github.com/Dogstudio/highway/releases/tag/v2.1.2) instead of `(to, location)` you should write `({ to, location })`. This might not look like a big change but for further updates it was important to group parameters in an object developers can destructure to letus add as much entries as we need to expose more informations if needed in the future.

Best regards,
Anthodpnt
